name: Node.js CD

on:
  push:
    branches: [main]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Build
        run: npm run build

      - name: Deploy
        run: pm2 static-page-server-8080 restart
